### ISSUE TITLE
Add Config files

### ISSUE THREAD

**Issue by pohotu3** [PulsePanda/Crystal-Home-Systems#70]
Some settings need to be accessed every-time the program runs, or have a different value on different computers. These settings should be put in config files so we don't have to rewrite portions of our code for out machines every time we get a new version.

C# has classes that handle this in the namespace System.Configuration.

**Comment by PulsePanda** [comment]
to add to this issue, if we're going to set up config files we should set up a "first time setup wizard" system for the SERVER side of the application, so that a new user can configure everything really easily. On top of this, before we make that wizard, we need to transition from console to GUI, linked at #28
